--- #---------------- Chaincode Service ---------------------
apiVersion: v1
kind: Service
metadata:
  name: chain-org
  labels:
    app: chain-org
spec:
  ports:
    - name: grpc
      port: 7052
      targetPort: 7052
  selector:
    app: chaincode-basic-org2
