apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  repositories: |
    - url: https://github.com/Nikhil007nsg/k8s-blockchain.git
      usernameSecret:
        name: github-secret
        key: username
      passwordSecret:
        name: github-secret
        key: password
