apiVersion: v1
kind: Secret
metadata:
  name: k8s-secret
  namespace: default
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogImJtbHJhR2xzYzJjNlRtbGphMEF4T1RrMSIKCQl9Cgl9Cn0=
